kind: ethereum/contract
name: MolochV1Template
network:
source:
  abi: V1Moloch
mapping:
  kind: ethereum/events
  apiVersion: 0.0.5
  language: wasm/assemblyscript
  file: ./src/v1-mapping.ts
  entities:
    - Moloch
    - Member
    - Vote
    - Proposal
    - Badge
  abis:
    - name: V1Moloch
      file: ./abis/V1Moloch.json
    - name: Guildbank
      file: ./abis/Guildbank.json
    - name: Erc20
      file: ./abis/Erc20.json
    - name: Erc20Bytes32
      file: ./abis/Erc20Bytes32.json
  eventHandlers:
    - event: "SummonComplete(indexed address,uint256)"
      handler: handleSummonComplete
    - event: >-
        SubmitProposal(uint256,indexed address,indexed address,indexed
        address,uint256,uint256)
      handler: handleSubmitProposal
    - event: "SubmitVote(indexed uint256,indexed address,indexed address,uint8)"
      handler: handleSubmitVote
    - event: >-
        ProcessProposal(indexed uint256,indexed address,indexed
        address,uint256,uint256,bool)
      handler: handleProcessProposal
    - event: "Ragequit(indexed address,uint256)"
      handler: handleRagequit
    - event: "Abort(indexed uint256,address)"
      handler: handleAbort
    - event: "UpdateDelegateKey(indexed address,address)"
      handler: handleUpdateDelegateKey
